"""Visitor photography — local uploads and legacy gallery downloads at build time."""

VISITOR_GALLERY = [
    {
        "url": "https://www.glavanipark.com/upload/katalog/2017-9-5_ljudski_katapult__atrakcija_broj_1.jpg",
        "image": "visitor-gallery-human-catapult-launch-14.webp",
        "en_alt": "Guest launched on the Human Catapult at Glavani Park, Istria Croatia",
        "hr_alt": "Gost lansiran na ljudskoj katapulti u Glavani Parku, Istria Hrvatska",
        "activities": ["human-catapult"],
        "home": True,
    },
    {
        "url": "https://www.glavanipark.com/upload/galerija/3/1838321.jpg",
        "image": "visitor-gallery-high-ropes-platform-13.webp",
        "en_alt": "Guest on a high-ropes platform with safety cables at Glavani Park, Istria",
        "hr_alt": "Gost na platformi visokih staza sa sigurnosnim užadima u Glavani Parku, Istria",
        "activities": ["20m-drop"],
        "home": False,
    },
    {
        "url": "https://www.glavanipark.com/upload/galerija/2/47510928.jpg",
        "image": "visitor-gallery-adventure-park-3.webp",
        "en_alt": "High-ropes course platforms and numbered routes at Glavani Park near Barban",
        "hr_alt": "Platforme visokih staza i označene rute u Glavani Parku kod Barbana",
        "activities": ["high-swing", "20m-drop"],
        "home": True,
    },
    {
        "url": "https://www.glavanipark.com/upload/galerija/1/35429019.jpg",
        "image": "visitor-gallery-park-grounds-5.webp",
        "en_alt": "Children on a suspended log obstacle wearing helmets and harnesses at Glavani Park",
        "hr_alt": "Djeca na visećoj gredi s kacigama i harnesima u Glavani Parku",
        "activities": ["high-swing"],
        "home": True,
    },
    {
        "url": "https://www.glavanipark.com/upload/galerija/4/38381595.jpg",
        "image": "visitor-gallery-school-group-7.webp",
        "en_alt": "School group in helmets and harnesses ready for the high-ropes course at Glavani Park",
        "hr_alt": "Školska grupa u kacigama i harnesima prije visokih staza u Glavani Parku",
        "activities": ["human-catapult"],
        "home": True,
    },
    {
        "url": "https://www.glavanipark.com/upload/galerija/5/38879031.jpg",
        "image": "visitor-gallery-group-event-10.webp",
        "en_alt": "Group of visitors in harnesses at Glavani Park between activities",
        "hr_alt": "Grupa posjetitelja u harnesima u Glavani Parku između aktivnosti",
        "activities": ["human-catapult", "high-swing"],
        "home": True,
    },
    {
        "url": "https://www.glavanipark.com/upload/galerija/3/44248599.jpg",
        "image": "visitor-gallery-zipline-trio-16.webp",
        "en_alt": "Three visitors on a suspended log high above the forest on the zipline course at Glavani Park, Istria",
        "hr_alt": "Tri posjetitelja na visećoj gredi visoko iznad šume na zipline stazi u Glavani Parku, Istria",
        "activities": [],
        "home": False,
    },
    {
        "image": "visitor-gallery-aerotrim-guest-19.webp",
        "en_alt": "Guest in the Aerotrim human gyroscope with instructor at Glavani Park, Istria",
        "hr_alt": "Gost u Aerotrima ljudskom žiroskopu uz instruktora u Glavani Parku, Istria",
        "activities": ["aerotrim"],
        "home": True,
        "local": True,
    },
    {
        "image": "visitor-gallery-climbing-wall-guest-20.webp",
        "en_alt": "Guest climbing the outdoor climbing wall at Glavani Park, Istria",
        "hr_alt": "Gost penje vanjski penjački zid u Glavani Parku, Istria",
        "activities": ["climbing-wall"],
        "home": True,
        "local": True,
    },
    {
        "image": "visitor-gallery-devils-causeway-guest-21.webp",
        "en_alt": "Guest on the Devil's Causeway high-ropes course at Glavani Park, Istria",
        "hr_alt": "Gost na Stazi Vražjeg puta u Glavani Parku, Istria",
        "activities": ["devils-causeway"],
        "home": True,
        "local": True,
    },
    {
        "image": "visitor-gallery-valley-zipline-staff-22.webp",
        "en_alt": "Guest riding the Valley Zipline through the oak forest valley at Glavani Park, Istria",
        "hr_alt": "Gost na dolinskoj zipline stazi kroz hrastovu dolinu u Glavani Parku, Istria",
        "activities": ["valley-zipline"],
        "home": True,
        "local": True,
    },
    {
        "image": "visitor-gallery-valley-zipline-staff-23.webp",
        "en_alt": "Instructor on the Big Zipline above the forest at Glavani Park, Istria",
        "hr_alt": "Instruktor na velikoj zipline iznad šume u Glavani Parku, Istria",
        "activities": ["valley-zipline"],
        "home": False,
        "local": True,
    },
    {
        "image": "visitor-gallery-valley-zipline-guest-24.webp",
        "en_alt": "Guest on the Valley Zipline at Glavani Park, Istria",
        "hr_alt": "Gost na dolinskoj zipline stazi u Glavani Parku, Istria",
        "activities": ["valley-zipline"],
        "home": False,
        "local": True,
    },
    {
        "image": "visitor-gallery-valley-zipline-guest-25.webp",
        "en_alt": "Guest on the Big Zipline with forest views at Glavani Park, Istria",
        "hr_alt": "Gost na velikoj zipline s pogledom na šumu u Glavani Parku, Istria",
        "activities": ["valley-zipline"],
        "home": False,
        "local": True,
    },
    {
        "image": "visitor-gallery-valley-zipline-amphitheatre-26.webp",
        "en_alt": "Valley Zipline amphitheatre and oak forest at Glavani Park, Istria",
        "hr_alt": "Amfiteatar dolinske zipline i hrastova šuma u Glavani Parku, Istria",
        "activities": ["valley-zipline"],
        "home": False,
        "local": True,
    },
    {
        "image": "visitor-gallery-treetop-course-guest-27.webp",
        "en_alt": "Guest on the treetop high-ropes course at Glavani Park, Istria",
        "hr_alt": "Gost na stazi u krošnjama u Glavani Parku, Istria",
        "activities": ["low-zipline"],
        "home": True,
        "local": True,
    },
    {
        "image": "visitor-gallery-treetop-course-guest-28.webp",
        "en_alt": "Guest crossing a treetop obstacle at Glavani Park, Istria",
        "hr_alt": "Gost prelazi prepreku na stazi u krošnjama u Glavani Parku, Istria",
        "activities": ["low-zipline"],
        "home": False,
        "local": True,
    },
    {
        "image": "visitor-gallery-treetop-course-staff-29.webp",
        "en_alt": "Guest on the treetop course with instructor at Glavani Park, Istria",
        "hr_alt": "Gost na stazi u krošnjama uz instruktora u Glavani Parku, Istria",
        "activities": ["training-route"],
        "home": True,
        "local": True,
    },
    {
        "image": "visitor-gallery-treetop-course-guest-30.webp",
        "en_alt": "Guest on a treetop platform at Glavani Park, Istria",
        "hr_alt": "Gost na platformi staze u krošnjama u Glavani Parku, Istria",
        "activities": ["low-zipline"],
        "home": False,
        "local": True,
    },
    {
        "image": "visitor-gallery-treetop-course-guest-31.webp",
        "en_alt": "Guest on the treetop course among oak trees at Glavani Park, Istria",
        "hr_alt": "Gost na stazi u krošnjama među hrastovima u Glavani Parku, Istria",
        "activities": ["low-zipline"],
        "home": False,
        "local": True,
    },
    {
        "image": "visitor-gallery-treetop-course-guest-32.webp",
        "en_alt": "Guest on the yellow training route treetop course at Glavani Park, Istria",
        "hr_alt": "Gost na žutoj trening ruti u krošnjama u Glavani Parku, Istria",
        "activities": ["training-route"],
        "home": False,
        "local": True,
    },
    {
        "image": "visitor-gallery-treetop-course-family-33.webp",
        "en_alt": "Family on the treetop training route at Glavani Park, Istria",
        "hr_alt": "Obitelj na trening ruti u krošnjama u Glavani Parku, Istria",
        "activities": ["training-route", "low-zipline"],
        "home": True,
        "local": True,
    },
    {
        "image": "visitor-gallery-park-sunrise-34.webp",
        "en_alt": "Morning sun over Glavani Park adventure park in Istria, Croatia",
        "hr_alt": "Jutarnje sunce nad avanturističkim parkom Glavani u Istri, Hrvatska",
        "activities": [],
        "home": True,
        "local": True,
    },
]

ACTIVITY_GALLERY_MAP: dict[str, list[str]] = {
    "human-catapult": [
        "visitor-gallery-human-catapult-launch-14.webp",
        "visitor-gallery-group-event-10.webp",
        "visitor-gallery-school-group-7.webp",
    ],
    "high-swing": [
        "visitor-gallery-park-grounds-5.webp",
        "visitor-gallery-adventure-park-3.webp",
        "visitor-gallery-group-event-10.webp",
    ],
    "training-route": [
        "visitor-gallery-treetop-course-family-33.webp",
        "visitor-gallery-treetop-course-staff-29.webp",
        "visitor-gallery-treetop-course-guest-32.webp",
    ],
    "low-zipline": [
        "visitor-gallery-treetop-course-guest-27.webp",
        "visitor-gallery-treetop-course-guest-30.webp",
        "visitor-gallery-treetop-course-family-33.webp",
        "visitor-gallery-treetop-course-guest-28.webp",
    ],
    "valley-zipline": [
        "visitor-gallery-valley-zipline-staff-22.webp",
        "visitor-gallery-valley-zipline-staff-23.webp",
        "visitor-gallery-valley-zipline-amphitheatre-26.webp",
        "visitor-gallery-valley-zipline-guest-24.webp",
    ],
    "devils-causeway": [
        "visitor-gallery-devils-causeway-guest-21.webp",
    ],
    "climbing-wall": [
        "visitor-gallery-climbing-wall-guest-20.webp",
    ],
    "aerotrim": [
        "visitor-gallery-aerotrim-guest-19.webp",
    ],
    "20m-drop": [
        "visitor-gallery-adventure-park-3.webp",
        "visitor-gallery-high-ropes-platform-13.webp",
    ],
}

HOME_GALLERY_IMAGES = [item["image"] for item in VISITOR_GALLERY if item.get("home")]

GALLERY_BY_IMAGE = {item["image"]: item for item in VISITOR_GALLERY}
