"""Visitor photography — local uploads and legacy gallery downloads at build time."""

VISITOR_GALLERY = [
    {
        "url": "https://www.glavanipark.com/upload/katalog/2017-9-5_ljudski_katapult__atrakcija_broj_1.jpg",
        "image": "visitor-gallery-human-catapult-launch-14.webp",
        "en_alt": "Guest launched on the Human Catapult at Glavani Park, Istria Croatia",
        "hr_alt": "Gost lansiran na ljudskoj katapulti u Glavani Parku, Istria Hrvatska",
        "activities": ["human-catapult"],
        "home": True,
    },
    {
        "url": "https://www.glavanipark.com/upload/galerija/3/1838321.jpg",
        "image": "visitor-gallery-high-ropes-platform-13.webp",
        "en_alt": "Guest on a high-ropes platform with safety cables at Glavani Park, Istria",
        "hr_alt": "Gost na platformi visokih staza sa sigurnosnim užadima u Glavani Parku, Istria",
        "activities": ["20m-drop"],
        "home": False,
    },
    {
        "url": "https://www.glavanipark.com/upload/galerija/2/47510928.jpg",
        "image": "visitor-gallery-adventure-park-3.webp",
        "en_alt": "High-ropes course platforms and numbered routes at Glavani Park near Barban",
        "hr_alt": "Platforme visokih staza i označene rute u Glavani Parku kod Barbana",
        "activities": ["high-swing", "20m-drop"],
        "home": True,
    },
    {
        "url": "https://www.glavanipark.com/upload/galerija/1/35429019.jpg",
        "image": "visitor-gallery-park-grounds-5.webp",
        "en_alt": "Children on a suspended log obstacle wearing helmets and harnesses at Glavani Park",
        "hr_alt": "Djeca na visećoj gredi s kacigama i harnesima u Glavani Parku",
        "activities": ["high-swing"],
        "home": True,
    },
    {
        "url": "https://www.glavanipark.com/upload/galerija/4/38381595.jpg",
        "image": "visitor-gallery-school-group-7.webp",
        "en_alt": "School group in helmets and harnesses ready for the high-ropes course at Glavani Park",
        "hr_alt": "Školska grupa u kacigama i harnesima prije visokih staza u Glavani Parku",
        "activities": ["human-catapult"],
        "home": True,
    },
    {
        "url": "https://www.glavanipark.com/upload/galerija/5/38879031.jpg",
        "image": "visitor-gallery-group-event-10.webp",
        "en_alt": "Group of visitors in harnesses at Glavani Park between activities",
        "hr_alt": "Grupa posjetitelja u harnesima u Glavani Parku između aktivnosti",
        "activities": ["human-catapult", "high-swing"],
        "home": True,
    },
    {
        "url": "https://www.glavanipark.com/upload/galerija/3/44248599.jpg",
        "image": "visitor-gallery-zipline-trio-16.webp",
        "en_alt": "Three visitors on a suspended log high above the forest on the zipline course at Glavani Park, Istria",
        "hr_alt": "Tri posjetitelja na visećoj gredi visoko iznad šume na zipline stazi u Glavani Parku, Istria",
        "activities": [],
        "home": False,
    },
    {
        "image": "visitor-gallery-aerotrim-guest-19.webp",
        "en_alt": "Guest in the Aerotrim human gyroscope with instructor at Glavani Park, Istria",
        "hr_alt": "Gost u Aerotrima ljudskom žiroskopu uz instruktora u Glavani Parku, Istria",
        "activities": ["aerotrim"],
        "home": True,
        "local": True,
    },
    {
        "image": "visitor-gallery-climbing-wall-guest-20.webp",
        "en_alt": "Guest climbing the outdoor climbing wall at Glavani Park, Istria",
        "hr_alt": "Gost penje vanjski penjački zid u Glavani Parku, Istria",
        "activities": ["climbing-wall"],
        "home": True,
        "local": True,
    },
    {
        "image": "visitor-gallery-devils-causeway-guest-21.webp",
        "en_alt": "Guest on the Devil's Causeway high-ropes course at Glavani Park, Istria",
        "hr_alt": "Gost na Stazi Vražjeg puta u Glavani Parku, Istria",
        "activities": ["devils-causeway"],
        "home": True,
        "local": True,
    },
    {
        "image": "visitor-gallery-valley-zipline-staff-22.webp",
        "en_alt": "Guest riding the Valley Zipline through the oak forest valley at Glavani Park, Istria",
        "hr_alt": "Gost na dolinskoj zipline stazi kroz hrastovu dolinu u Glavani Parku, Istria",
        "activities": ["valley-zipline"],
        "home": True,
        "local": True,
    },
    {
        "image": "visitor-gallery-valley-zipline-staff-23.webp",
        "en_alt": "Instructor on the Big Zipline above the forest at Glavani Park, Istria",
        "hr_alt": "Instruktor na velikoj zipline iznad šume u Glavani Parku, Istria",
        "activities": ["valley-zipline"],
        "home": False,
        "local": True,
    },
    {
        "image": "visitor-gallery-valley-zipline-guest-24.webp",
        "en_alt": "Guest on the Valley Zipline at Glavani Park, Istria",
        "hr_alt": "Gost na dolinskoj zipline stazi u Glavani Parku, Istria",
        "activities": ["valley-zipline"],
        "home": False,
        "local": True,
    },
    {
        "image": "visitor-gallery-valley-zipline-guest-25.webp",
        "en_alt": "Guest on the Big Zipline with forest views at Glavani Park, Istria",
        "hr_alt": "Gost na velikoj zipline s pogledom na šumu u Glavani Parku, Istria",
        "activities": ["valley-zipline"],
        "home": False,
        "local": True,
    },
    {
        "image": "visitor-gallery-valley-zipline-amphitheatre-26.webp",
        "en_alt": "Valley Zipline amphitheatre and oak forest at Glavani Park, Istria",
        "hr_alt": "Amfiteatar dolinske zipline i hrastova šuma u Glavani Parku, Istria",
        "activities": ["valley-zipline"],
        "home": False,
        "local": True,
    },
    {
        "image": "visitor-gallery-treetop-course-guest-27.webp",
        "en_alt": "Guest on the treetop high-ropes course at Glavani Park, Istria",
        "hr_alt": "Gost na stazi u krošnjama u Glavani Parku, Istria",
        "activities": ["low-zipline"],
        "home": True,
        "local": True,
    },
    {
        "image": "visitor-gallery-treetop-course-guest-28.webp",
        "en_alt": "Guest crossing a treetop obstacle at Glavani Park, Istria",
        "hr_alt": "Gost prelazi prepreku na stazi u krošnjama u Glavani Parku, Istria",
        "activities": ["low-zipline"],
        "home": False,
        "local": True,
    },
    {
        "image": "visitor-gallery-treetop-course-staff-29.webp",
        "en_alt": "Guest on the treetop course with instructor at Glavani Park, Istria",
        "hr_alt": "Gost na stazi u krošnjama uz instruktora u Glavani Parku, Istria",
        "activities": ["training-route"],
        "home": True,
        "local": True,
    },
    {
        "image": "visitor-gallery-treetop-course-guest-30.webp",
        "en_alt": "Guest on a treetop platform at Glavani Park, Istria",
        "hr_alt": "Gost na platformi staze u krošnjama u Glavani Parku, Istria",
        "activities": ["low-zipline"],
        "home": False,
        "local": True,
    },
    {
        "image": "visitor-gallery-treetop-course-guest-31.webp",
        "en_alt": "Guest on the treetop course among oak trees at Glavani Park, Istria",
        "hr_alt": "Gost na stazi u krošnjama među hrastovima u Glavani Parku, Istria",
        "activities": ["low-zipline"],
        "home": False,
        "local": True,
    },
    {
        "image": "visitor-gallery-treetop-course-guest-32.webp",
        "en_alt": "Guest on the yellow training route treetop course at Glavani Park, Istria",
        "hr_alt": "Gost na žutoj trening ruti u krošnjama u Glavani Parku, Istria",
        "activities": ["training-route"],
        "home": False,
        "local": True,
    },
    {
        "image": "visitor-gallery-treetop-course-family-33.webp",
        "en_alt": "Family on the treetop training route at Glavani Park, Istria",
        "hr_alt": "Obitelj na trening ruti u krošnjama u Glavani Parku, Istria",
        "activities": ["training-route", "low-zipline"],
        "home": True,
        "local": True,
    },
    {
        "image": "visitor-gallery-park-sunrise-34.webp",
        "en_alt": "Morning sun over Glavani Park adventure park in Istria, Croatia",
        "hr_alt": "Jutarnje sunce nad avanturističkim parkom Glavani u Istri, Hrvatska",
        "activities": [],
        "home": True,
        "local": True,
    },
]

ACTIVITY_GALLERY_ITEMS: dict[str, list[dict[str, str]]] = {
    "human-catapult": [
        {"type": "image", "ref": "visitor-gallery-human-catapult-launch-14.webp"},
        {"type": "video", "ref": "0ZHvelhfYFU"},
        {"type": "video", "ref": "gptE-l0kJ8E"},
        {"type": "video", "ref": "sN78QtB-nI0"},
        {"type": "video", "ref": "hJPwH_bxnWQ"},
    ],
    "high-swing": [
        {"type": "image", "ref": "visitor-gallery-park-grounds-5.webp"},
        {"type": "video", "ref": "3OFULwzXtmU"},
        {"type": "video", "ref": "HvBqYKEk9TM"},
        {"type": "video", "ref": "8C07_QgmaPo"},
    ],
    "training-route": [
        {"type": "image", "ref": "visitor-gallery-treetop-course-family-33.webp"},
        {"type": "video", "ref": "QVz5eBaj02o"},
        {"type": "image", "ref": "visitor-gallery-treetop-course-staff-29.webp"},
        {"type": "video", "ref": "7URtyBlOHIQ"},
        {"type": "image", "ref": "visitor-gallery-treetop-course-guest-32.webp"},
        {"type": "video", "ref": "ZMgFGX1Z6N4"},
    ],
    "low-zipline": [
        {"type": "image", "ref": "visitor-gallery-treetop-course-guest-27.webp"},
        {"type": "video", "ref": "QVz5eBaj02o"},
        {"type": "image", "ref": "visitor-gallery-treetop-course-guest-30.webp"},
        {"type": "video", "ref": "FQC8hqvD4lg"},
        {"type": "image", "ref": "visitor-gallery-treetop-course-family-33.webp"},
        {"type": "video", "ref": "7URtyBlOHIQ"},
        {"type": "image", "ref": "visitor-gallery-treetop-course-guest-28.webp"},
    ],
    "valley-zipline": [
        {"type": "image", "ref": "visitor-gallery-valley-zipline-staff-22.webp"},
        {"type": "video", "ref": "aHBpvX1zeio"},
        {"type": "video", "ref": "DWMl2hZGARU"},
        {"type": "video", "ref": "CrRIcIfXt2w"},
        {"type": "video", "ref": "sW0xolt5cRw"},
        {"type": "video", "ref": "w7GOLClznl4"},
        {"type": "image", "ref": "visitor-gallery-valley-zipline-staff-23.webp"},
        {"type": "video", "ref": "-MG0CxMpNww"},
        {"type": "video", "ref": "HxDrfD2vtbo"},
        {"type": "video", "ref": "j_5MqCAGnCg"},
        {"type": "image", "ref": "visitor-gallery-valley-zipline-guest-24.webp"},
        {"type": "video", "ref": "uUT4xGBRa8Y"},
    ],
    "devils-causeway": [
        {"type": "image", "ref": "visitor-gallery-devils-causeway-guest-21.webp"},
        {"type": "video", "ref": "0hSnp49CcZ8"},
        {"type": "video", "ref": "6p-7QWy3z30"},
    ],
    "climbing-wall": [
        {"type": "image", "ref": "visitor-gallery-climbing-wall-guest-20.webp"},
    ],
    "aerotrim": [
        {"type": "image", "ref": "visitor-gallery-aerotrim-guest-19.webp"},
        {"type": "video", "ref": "HdOXPwBiqq8"},
    ],
    "20m-drop": [
        {"type": "video", "ref": "NAhsPEJW4ig"},
        {"type": "video", "ref": "UiZ6ZsU2hZY"},
    ],
}

VISITOR_VIDEOS: dict[str, dict[str, str | list[str]]] = {
    "0ZHvelhfYFU": {
        "en_title": "Human Catapult at Glavani Park",
        "hr_title": "Ljudska katapulta u Glavani Parku",
        "activities": ["human-catapult"],
    },
    "gptE-l0kJ8E": {
        "en_title": "Human Catapult launch at Glavani Park",
        "hr_title": "Lansiranje na ljudskoj katapulti u Glavani Parku",
        "activities": ["human-catapult"],
    },
    "sN78QtB-nI0": {
        "en_title": "Human Catapult ride at Glavani Park",
        "hr_title": "Vožnja ljudskom katapultom u Glavani Parku",
        "activities": ["human-catapult"],
    },
    "hJPwH_bxnWQ": {
        "en_title": "Human Catapult highlights at Glavani Park",
        "hr_title": "Najbolji trenuci ljudske katapulti u Glavani Parku",
        "activities": ["human-catapult"],
    },
    "3OFULwzXtmU": {
        "en_title": "High Swing at Glavani Park",
        "hr_title": "Visoka ljuljačka u Glavani Parku",
        "activities": ["high-swing"],
        "orientation": "landscape",
    },
    "HvBqYKEk9TM": {
        "en_title": "High Swing ride at Glavani Park",
        "hr_title": "Vožnja visokom ljuljačkom u Glavani Parku",
        "activities": ["high-swing"],
        "orientation": "landscape",
    },
    "8C07_QgmaPo": {
        "en_title": "High Swing in the oak forest at Glavani Park",
        "hr_title": "Visoka ljuljačka u hrastovoj šumi Glavani Parka",
        "activities": ["high-swing"],
    },
    "QVz5eBaj02o": {
        "en_title": "Treetop Course at Glavani Park",
        "hr_title": "Staza u krošnjama u Glavani Parku",
        "activities": ["training-route", "low-zipline"],
    },
    "7URtyBlOHIQ": {
        "en_title": "Treetop Course obstacles at Glavani Park",
        "hr_title": "Prepreke na stazi u krošnjama u Glavani Parku",
        "activities": ["training-route", "low-zipline"],
    },
    "ZMgFGX1Z6N4": {
        "en_title": "Treetop Course adventure at Glavani Park",
        "hr_title": "Avantura na stazi u krošnjama u Glavani Parku",
        "activities": ["training-route"],
    },
    "FQC8hqvD4lg": {
        "en_title": "Treetop Course zipline at Glavani Park",
        "hr_title": "Zipline na stazi u krošnjama u Glavani Parku",
        "activities": ["low-zipline"],
        "orientation": "landscape",
    },
    "aHBpvX1zeio": {
        "en_title": "Valley Zipline at Glavani Park",
        "hr_title": "Dolinski zipline u Glavani Parku",
        "activities": ["valley-zipline"],
        "orientation": "landscape",
    },
    "DWMl2hZGARU": {
        "en_title": "Valley Zipline ride at Glavani Park",
        "hr_title": "Vožnja dolinskom ziplinom u Glavani Parku",
        "activities": ["valley-zipline"],
        "orientation": "landscape",
    },
    "CrRIcIfXt2w": {
        "en_title": "Valley Zipline through the forest at Glavani Park",
        "hr_title": "Dolinski zipline kroz šumu u Glavani Parku",
        "activities": ["valley-zipline"],
        "orientation": "landscape",
    },
    "sW0xolt5cRw": {
        "en_title": "Valley Zipline launch at Glavani Park",
        "hr_title": "Polazak dolinske zipline u Glavani Parku",
        "activities": ["valley-zipline"],
        "orientation": "landscape",
    },
    "w7GOLClznl4": {
        "en_title": "Valley Zipline amphitheatre at Glavani Park",
        "hr_title": "Amfiteatar dolinske zipline u Glavani Parku",
        "activities": ["valley-zipline"],
        "orientation": "landscape",
    },
    "-MG0CxMpNww": {
        "en_title": "Valley Zipline at Glavani Park",
        "hr_title": "Dolinski zipline u Glavani Parku",
        "activities": ["valley-zipline"],
    },
    "uUT4xGBRa8Y": {
        "en_title": "Valley Zipline through the forest at Glavani Park",
        "hr_title": "Dolinski zipline kroz šumu u Glavani Parku",
        "activities": ["valley-zipline"],
    },
    "HxDrfD2vtbo": {
        "en_title": "Valley Zipline from the launch platform at Glavani Park",
        "hr_title": "Dolinski zipline s platforme u Glavani Parku",
        "activities": ["valley-zipline"],
    },
    "j_5MqCAGnCg": {
        "en_title": "Double Valley Zipline run at Glavani Park",
        "hr_title": "Dvostruka vožnja dolinskom ziplinom u Glavani Parku",
        "activities": ["valley-zipline"],
    },
    "0hSnp49CcZ8": {
        "en_title": "Devil's Causeway Course at Glavani Park",
        "hr_title": "Staza Vražjeg puta u Glavani Parku",
        "activities": ["devils-causeway"],
        "orientation": "landscape",
    },
    "6p-7QWy3z30": {
        "en_title": "Starting the Devil's Causeway Course at Glavani Park",
        "hr_title": "Početak Staze Vražjeg puta u Glavani Parku",
        "activities": ["devils-causeway"],
    },
    "HdOXPwBiqq8": {
        "en_title": "Aerotrim human gyroscope at Glavani Park",
        "hr_title": "Aerotrim ljudski žiroskop u Glavani Parku",
        "activities": ["aerotrim"],
    },
    "NAhsPEJW4ig": {
        "en_title": "20m Quick Jump at Glavani Park",
        "hr_title": "Brzi skok s 20 m u Glavani Parku",
        "activities": ["20m-drop"],
    },
    "UiZ6ZsU2hZY": {
        "en_title": "Quick Jump highlights at Glavani Park",
        "hr_title": "Najbolji trenuci brzog skoka u Glavani Parku",
        "activities": ["20m-drop"],
    },
}

# Backwards-compatible image-only map (e.g. tests or tooling).
ACTIVITY_GALLERY_MAP: dict[str, list[str]] = {
    slug: [item["ref"] for item in items if item["type"] == "image"]
    for slug, items in ACTIVITY_GALLERY_ITEMS.items()
}

HOME_GALLERY_IMAGES = [item["image"] for item in VISITOR_GALLERY if item.get("home")]

GALLERY_BY_IMAGE = {item["image"]: item for item in VISITOR_GALLERY}
